[2023-10-31T21:27:32.374-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: fhv_ml_model_training.build_machine_learning_model manual__2023-11-01T02:27:27.602916+00:00 [queued]>
[2023-10-31T21:27:32.386-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: fhv_ml_model_training.build_machine_learning_model manual__2023-11-01T02:27:27.602916+00:00 [queued]>
[2023-10-31T21:27:32.386-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-10-31T21:27:32.386-0500] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-10-31T21:27:32.386-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-10-31T21:27:32.397-0500] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): build_machine_learning_model> on 2023-11-01 02:27:27.602916+00:00
[2023-10-31T21:27:32.402-0500] {standard_task_runner.py:55} INFO - Started process 602239 to run task
[2023-10-31T21:27:32.405-0500] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'fhv_ml_model_training', 'build_machine_learning_model', 'manual__2023-11-01T02:27:27.602916+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_train_ml_model.py', '--cfg-path', '/tmp/tmplbz1k8o4']
[2023-10-31T21:27:32.407-0500] {standard_task_runner.py:83} INFO - Job 33: Subtask build_machine_learning_model
[2023-10-31T21:27:32.497-0500] {task_command.py:389} INFO - Running <TaskInstance: fhv_ml_model_training.build_machine_learning_model manual__2023-11-01T02:27:27.602916+00:00 [running]> on host DESKTOP-D8R6NL8.
[2023-10-31T21:27:32.599-0500] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_ml_model_training
AIRFLOW_CTX_TASK_ID=build_machine_learning_model
AIRFLOW_CTX_EXECUTION_DATE=2023-11-01T02:27:27.602916+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-01T02:27:27.602916+00:00
[2023-10-31T21:27:32.600-0500] {dag_train_ml_model.py:109} INFO - Loading the train and validation datasets...
[2023-10-31T21:27:35.991-0500] {dag_train_ml_model.py:112} INFO - The datasets were loaded properly!!!
[2023-10-31T21:27:35.991-0500] {dag_train_ml_model.py:116} INFO - Pre-processing the train and validation datasets...
[2023-10-31T21:27:36.115-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/airflow/dags/dag_train_ml_model.py", line 117, in buid_machine_learning_model
    df_train_processed = prepare_features(df_train, categorical)
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/airflow/dags/dag_train_ml_model.py", line 27, in prepare_features
    df = df[(df.drop_duration >= 1) & (df.duration <= 60)].copy()
  File "/home/oscar_rincon/code/oscar-rincon/ml-engineering-course/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'drop_duration'
[2023-10-31T21:27:36.166-0500] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=fhv_ml_model_training, task_id=build_machine_learning_model, execution_date=20231101T022727, start_date=20231101T022732, end_date=20231101T022736
[2023-10-31T21:27:36.188-0500] {standard_task_runner.py:100} ERROR - Failed to execute job 33 for task build_machine_learning_model ('DataFrame' object has no attribute 'drop_duration'; 602239)
[2023-10-31T21:27:36.246-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-10-31T21:27:36.281-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
